- package.json
- packages/storefront-lwc/package.json
- yarn.lock
Force to use `js-yaml@3.13.1`. This is a dependency downstream from `lwc-services`
> Fix dependency warning

- packages/@sfcc-bff/productapi/src/api/schema/productDetailsResolvers.js
- packages/@sfcc-bff/productapi/src/api/schema/productSearchResolvers.js
Fix: changed the prodcutDetailsResolver to not include expand in query params
> Fix: changed the prodcutDetailsResolver to not include expand in query params

- package.json
- packages/@sfcc-bff/productapi/package.json
- packages/@sfcc-core/apiconfig/package.json
- packages/@sfcc-core/core-graphql/package.json
- packages/@sfcc-core/core/package.json
- packages/@sfcc-core/logger/package.json
- packages/sfcc-base/package.json
- packages/storefront-lwc/package.json
- yarn.lock
UPDATE: Changed version numbers to 1.0.0-alpha.1 for uniformity and for a good starting point
> UPDATE: Changed version numbers to 1.0.0-alpha.1 everywhere

- packages/storefront-lwc/src/modules/commerce/productPrice/productPrice.scss
- packages/storefront-lwc/src/modules/commerce/productSearchResults/productSearchResults.html
- yarn.lock
Added git commit signing, fixed UX
> abkap02 | GUS W-7208228, and W-7208631

- docs/componentExtension.md
This PR will be checked into integration as a documentation.
> New : add component extension readme

- docs/componentExtension.md
I made edits to the componentExtension.md file. Please take a look to make sure I didn't mess up your intended meaning. Thanks!
> Pauls edits to zi component extension2

- packages/storefront-lwc/package.json
- packages/storefront-lwc/src/modules/commerce/router/router.js
- packages/storefront-lwc/src/modules/commerce/searchBar/searchBar.js
PR for Search - Keyword Search Encoding for Security Best Practices (W-6984514)
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007r283IAA/view
> new: Search - Keyword Search Encoding for Security Best Practices (W-6984514)

- packages/@sfcc-bff/cartapi/src/api/schema/cartResolvers.js
- packages/@sfcc-bff/productapi/src/api/models/SearchResult.js
- packages/@sfcc-bff/productapi/src/api/schema/productDetailsResolvers.js
- packages/@sfcc-bff/productapi/src/api/schema/productSearchResolvers.js
- packages/@sfcc-bff/productapi/src/api/schema/productSearchTypeDef.js
- packages/@sfcc-core/core-graphql/src/graphql.ts
- packages/storefront-lwc/src/modules/commerce/cart/cart.js
- packages/storefront-lwc/src/modules/commerce/data/productsearchadaptor.js
- packages/storefront-lwc/src/modules/commerce/productDetail/productDetail.js
- packages/storefront-lwc/src/modules/commerce/productList/productList.html
- packages/storefront-lwc/src/modules/commerce/productList/productList.js
- packages/storefront-lwc/src/modules/commerce/productSearchResults/productSearchResults.html
- packages/storefront-lwc/src/modules/commerce/productSearchResults/productSearchResults.js
- packages/storefront-lwc/src/modules/commerce/router/router.js
- packages/storefront-lwc/src/modules/commerce/searchBar/searchBar.js
- packages/storefront-lwc/src/modules/commerce/searchSort/searchSort.html
- packages/storefront-lwc/src/modules/commerce/searchSort/searchSort.js
- yarn.lock
Please review [W-7034305: Get Product Search Sorting Rules from BFF](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B0000007rfOJIAY/view)
> abkap02-search-sorting-rules

- packages/storefront-lwc/package.json
- packages/storefront-lwc/scripts/runtime.mjs
- packages/storefront-lwc/scripts/sample-app.mjs
- yarn.lock
Fixes https://github.com/SalesforceCommerceCloud/sfcc-sample-apps/issues/127
> Fix running the app on windows by adding cross-env

- packages/storefront-lwc/package.json
Cannot be a dev dependency because it is used in the main startup
> Fix cross env to be a main dependency

- packages/storefront-lwc/src/modules/commerce/productSearchResults/productSearchResults.html
- packages/storefront-lwc/src/modules/commerce/productSearchResults/productSearchResults.js
- packages/storefront-lwc/src/modules/commerce/productSearchResults/productSearchResults.scss
Please review - [Search no result page should be cleaned up (W-7246249)](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07B000000878meIAA/view)
> abkap02 search no result page

- packages/@sfcc-bff/productapi/package.json
- yarn.lock
Update(@sfcc-bff) commerce-sdk to v1.3.0-alpha.9
> Update(@sfcc-bff) commerce-sdk to v1.3.0-alpha.9

- .circleci/config.yml
Heroku already is hooked into the git repo and will deploy independent
of circle ci
> Fix the build by removing deploy to heroku

- packages/storefront-lwc/src/modules/commerce/router/router.js
This should resolve some of the XSS concerns
> Fix(storefront-lwc) remove innerHTML in favor of imperative dom creation

- README.md
- packages/@sfcc-core/core-graphql/src/graphql.ts
- packages/@sfcc-core/core/src/types.ts
- packages/storefront-lwc/scripts/runtime.js
This allows us to use the sample app bff to get data in other contexts
> Add cors to the sample app

- PULL_REQUEST_TEMPLATE.md
This is a check list for making sure all areas are covered in a PR before we merge the code. Have a look and let me know if something should be changed, added or removed. The list is a subset of our team's DOD (refer to Quip doc).
> New: Adding a PR checklist to the master branch

- packages/@sfcc-bff/basketapi/src/api/schema/basketResolvers.ts
- packages/@sfcc-bff/productapi/src/api/schema/productDetailsResolvers.js
- packages/@sfcc-bff/productapi/src/api/schema/productSearchResolvers.js
- packages/storefront-lwc/src/modules/commerce/api/client.js
- packages/storefront-lwc/src/modules/commerce/productDetail/productDetail.js
> Update: the error handling in basketapi, productapi, and on the clientt (W-7361704)

- packages/storefront-lwc/src/modules/commerce/basketTotals/basketTotals.html
- packages/storefront-lwc/src/modules/commerce/basketTotals/basketTotals.js
- packages/storefront-lwc/src/modules/commerce/coupons/coupons.html
- packages/storefront-lwc/src/modules/commerce/total/total.html
- packages/storefront-lwc/src/modules/commerce/total/total.js
Update: Fixed some UX styling for Promo code and Order totals
> Update: Fixed some UX styling for Promo code and Order totals

- packages/storefront-lwc/scripts/runtime.js
> Update: change the cookie to have a strict same-site policy

- packages/storefront-lwc/src/modules/commerce/storeFront/storeFront.js
> Fix(storefront-lwc): fix infinite loop possibility on error handling

- packages/storefront-lwc/package.json
- packages/storefront-lwc/scripts/rollup.config.js
- packages/storefront-lwc/scripts/runtime.js
- yarn.lock
1. Fix lwc to output proper sourcemaps
2. Add live reload
3. Fix express-session warnings
> Fix(storefront-lwc): build fixes

- packages/storefront-lwc/src/modules/commerce/basket/basket.html
- packages/storefront-lwc/src/modules/commerce/contextHeading/contextHeading.html
- packages/storefront-lwc/src/modules/commerce/contextHeading/contextHeading.js
- packages/storefront-lwc/src/modules/commerce/contextHeading/contextHeading.scss
- packages/storefront-lwc/src/modules/commerce/productSearchResults/productSearchResults.html
- packages/storefront-lwc/src/modules/commerce/productSearchResults/productSearchResults.js
> Adiep new app header

- README.md
- docs/architecture.md
- packages/storefront-lwc/src/modules/commerce/basket/basket.html
- packages/storefront-lwc/src/modules/commerce/basket/readme.md
- packages/storefront-lwc/src/modules/commerce/coupons/coupons.html
> New : Basket component documentation

- packages/storefront-lwc/__mocks__/apollo-client.js
- packages/storefront-lwc/package.json
- packages/storefront-lwc/src/modules/commerce/productDetail/__tests__/__snapshots__/productDetail.test.js.snap
- packages/storefront-lwc/src/modules/commerce/productDetail/__tests__/productDetail.test.js
> Update(storefront-lwc): add tests for the product detail page

- PULL_REQUEST_TEMPLATE.md
- yarn.lock
> Fix integration

- packages/storefront-lwc/__mocks__/apollo-client.js
- packages/storefront-lwc/__mocks__/lwce-link/lwce-link.html
- packages/storefront-lwc/__mocks__/lwce-link/lwce-link.js
- packages/storefront-lwc/package.json
- packages/storefront-lwc/src/modules/commerce/basket/__tests__/__snapshots__/basket.test.js.snap
- packages/storefront-lwc/src/modules/commerce/basket/__tests__/basket.test.js
- packages/storefront-lwc/src/modules/commerce/basket/basket.html
- packages/storefront-lwc/src/modules/commerce/basket/basket.js
- packages/storefront-lwc/src/modules/commerce/productDetail/__tests__/productDetail.test.js
- packages/storefront-lwc/src/modules/commerce/testData/testData.js
- yarn.lock
> New(storefront-lwc) Add basket unit tests

- packages/storefront-lwc/src/modules/commerce/basket/basket.html
- packages/storefront-lwc/src/modules/commerce/checkout/__tests__/__snapshots__/checkout.test.js.snap
- packages/storefront-lwc/src/modules/commerce/checkout/__tests__/checkout.test.js
- packages/storefront-lwc/src/modules/commerce/checkout/checkout.html
- packages/storefront-lwc/src/modules/commerce/checkout/checkout.js
- packages/storefront-lwc/src/modules/commerce/checkoutPayment/checkoutPayment.html
- packages/storefront-lwc/src/modules/commerce/checkoutPayment/checkoutPayment.js
- packages/storefront-lwc/src/modules/commerce/checkoutShipping/checkoutShipping.html
- packages/storefront-lwc/src/modules/commerce/checkoutShipping/checkoutShipping.js
- packages/storefront-lwc/src/modules/commerce/checkoutSummary/checkoutSummary.html
- packages/storefront-lwc/src/modules/commerce/checkoutSummary/checkoutSummary.js
- packages/storefront-lwc/src/modules/commerce/storeFront/storeFront.html
> New(storefront-lwc): Add a base component for checkout (W-6814605)

- packages/storefront-lwc/src/modules/commerce/basket/__tests__/basket.test.js
- packages/storefront-lwc/src/modules/commerce/checkout/__tests__/checkout.test.js
- packages/storefront-lwc/src/modules/commerce/productDetail/__tests__/__snapshots__/productDetail.test.js.snap
- packages/storefront-lwc/src/modules/commerce/productDetail/__tests__/productDetail.test.js
- packages/storefront-lwc/src/modules/commerce/productDetail/productDetail.html
- packages/storefront-lwc/src/modules/commerce/productDetail/productDetail.js
- packages/storefront-lwc/src/modules/commerce/productDetail/productDetail.scss
- packages/storefront-lwc/src/modules/commerce/productImageCarousel/__tests__/__snapshots__/productImageCarousel.test.js.snap
- packages/storefront-lwc/src/modules/commerce/productImageCarousel/__tests__/productImageCarousel.test.js
- packages/storefront-lwc/src/modules/commerce/productImageCarousel/productImageCarousel.html
- packages/storefront-lwc/src/modules/commerce/productImageCarousel/productImageCarousel.js
- packages/storefront-lwc/src/modules/commerce/productImageCarousel/productImageCarousel.scss
- packages/storefront-lwc/src/modules/commerce/testHelpers/testHelpers.js
> New(storefront-lwc): Move image carousel into a separate component

- docs/sessionManagement.md
- packages/storefront-lwc/scripts/runtime.js
> update: customer id

- packages/storefront-lwc/__mocks__/apollo-client.js
- packages/storefront-lwc/__mocks__/router.js
- packages/storefront-lwc/package.json
- packages/storefront-lwc/src/index.js
- packages/storefront-lwc/src/modules/commerce/basket/__tests__/basket.test.js
- packages/storefront-lwc/src/modules/commerce/productDetail/__tests__/productDetail.test.js
- yarn.lock
The latest version of LWC had a breaking change with wire adapters.
Both @lwce/router and @lwce/apollo-client had to get changed. It should
be seamless for the sampleapp though. :)
> Chore: upgrade to the latest LWC

- README.md
> Doc: Updating the README.md file to fix errors and add information.

- packages/@sfcc-bff/productapi/package.json
- packages/storefront-lwc/package.json
- yarn.lock
> Chore(release): publish v1.0.0-alpha.4

- packages/@sfcc-bff/basketapi/src/api/models/Basket.ts
- packages/@sfcc-bff/basketapi/src/api/schema/basketResolvers.ts
- packages/@sfcc-bff/productapi/package.json
- yarn.lock
> Update for new sdk version 2.0.0

- CONTRIBUTING.md
- README.md
> Doc: Updating md files to remove mention of the integration branch.

- README.md
> Update: add archive message to the repo
